export const correctQuery = 'select * from B2CEUSWC.XMQTCATENTRELDATA FETCH FIRST 1 ROWS ONLY';
export const wrongQuery = 'select * from B2CEUSWC.NEVEREXIST FETCH FIRST 1 ROWS ONLY';
export const hardQuery = `WITH query1 AS
(SELECT *
 FROM B2CEUSWC.XMQTSKUPRICEDATA CP
 WHERE CP.TRADEPOSCN_ID = 4000000000000000207
   AND CP.WASPRICE * 0.5 = CP.CURRENTPRICE),
   query2 AS
(SELECT INV.CATENTRY_ID
 FROM query1 CP
 JOIN B2CEUSWC.INVENTORY INV ON INV.CATENTRY_ID = CP.CATENTRY_ID
 WHERE INV.QUANTITY > 50
   AND INV.QUANTITYMEASURE='C62'
   AND INV.FFMCENTER_ID IN
     (SELECT FFMCENTER_ID
      FROM B2CEUSWC.FFMCENTER
      WHERE NAME = 'TommyHilfiger'))
SELECT CT.STYLE_ID,
     CT.STYLECOLOUR_ID,
     CT.STYLE_PARTNUMBER,
     CT.STYLECOLOUR_PARTNUMBER
FROM B2CEUSWC.XMQTCATENTRELDATA CT
LEFT JOIN query2 INV ON CT.SKU_ID = INV.CATENTRY_ID
GROUP BY STYLE_ID,
       STYLECOLOUR_ID,
       CT.STYLE_PARTNUMBER,
       CT.STYLECOLOUR_PARTNUMBER FETCH FIRST 10 ROWS ONLY`;

export const styleColourIdList = 'p1307621,p1327599,p1327871'.split(',');

export const ckSapQuery = `SELECT DISTINCT CT.STYLE_ID,
CT.STYLE_PARTNUMBER,
CT.STYLECOLOUR_ID,
CT.STYLECOLOUR_PARTNUMBER,
CT.SKU_ID,
CT.SKU_PARTNUMBER
FROM B2CEUSWC.XMQTCATENTRELDATA CT
JOIN B2CEUSWC.INVENTORY INV ON CT.SKU_ID = INV.CATENTRY_ID
AND INV.QUANTITYMEASURE = 'C62'
AND FFMCENTER_ID = 715838485
AND INV.QUANTITY >= 100
FETCH FIRST 100 ROWS ONLY
WITH UR`;

export const thSapQuery = `SELECT DISTINCT CT.STYLE_ID,
CT.STYLE_PARTNUMBER,
CT.STYLECOLOUR_ID,
CT.STYLECOLOUR_PARTNUMBER,
CT.SKU_ID,
CT.SKU_PARTNUMBER
FROM B2CEUSWC.XMQTCATENTRELDATA CT
JOIN B2CEUSWC.INVENTORY INV ON CT.SKU_ID = INV.CATENTRY_ID
AND INV.QUANTITYMEASURE = 'C62'
AND FFMCENTER_ID = 715838484
AND INV.QUANTITY >= 100
FETCH FIRST 100 ROWS ONLY
WITH UR`;
